LXX = g++

all:
	$(LXX) -std=c++17 -o entity_example entityexample.cpp -lkoolengine
	$(LXX) -std=c++17 -o scene_test scenetest.cpp -lkoolengine
	$(LXX) -std=c++17 -o entity_scene scenent.cpp -lkoolengine -lSDL2
